export const MEDIUM_MOBILE_BREAKPOINT = 360;
export const LARGE_MOBILE_BREAKPOINT = 400;
export const TABLET_BREAKPOINT = 744;
export const DESKTOP_BREAKPOINT = 1200;
export const LARGE_DESKTOP_BREAKPOINT = 1440;
